spring.application.name=knowledge-portal
server.port=8010

spring.datasource.url=jdbc:postgresql://localhost:5432/knowledge_portal
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.cors.allowed-origins=http://localhost:8005,http://127.0.0.1:8005,http://localhost:5173,http://127.0.0.1:5173
