spring.application.name=knowledge-portal
server.port=8010

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/knowledge_portal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:*}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://admin:admin123@cluster0.soaqc2y.mongodb.net/sec?retryWrites=true&w=majority&appName=Cluster0}
